services:
  secom_admin:
    image: node:18-alpine
    container_name: secom_admin
    user: root
    working_dir: /usr/src/app
    volumes:
      - jenkins_jenkins_home:/usr/src/app
      - /home/nghiant/projects/ce/secom:/usr/src/app/workspace/secom/admin
    ports:
      - "5011:3000"
    command: >
      sh -c "cd workspace/secom/admin &&
             npm ci &&
             npm run build &&
             npm install -g serve &&
             serve -s build -l 3000"

  secom_client:
    image: node:18-alpine
    container_name: secom_client
    user: root
    working_dir: /usr/src/app
    volumes:
      - jenkins_jenkins_home:/usr/src/app
      - /home/nghiant/projects/ce/secom:/usr/src/app/workspace/secom/client
    ports:
      - "5013:3000"
    command: >
      sh -c "cd workspace/secom/client &&
             npm ci &&
             npm run build &&
             npm install -g serve &&
             serve -s build -l 3000"

  secom_server:
    image: node:18-alpine
    container_name: secom_server
    user: root
    working_dir: /usr/src/app
    volumes:
      - jenkins_jenkins_home:/usr/src/app
      - /home/nghiant/projects/ce/secom:/usr/src/app/workspace/secom/server
    ports:
      - "5012:5000"
    command: >
      sh -c "cd workspace/secom/server &&
             npm ci &&
             npm install -g serve &&
             serve -s build -l 5000"

volumes:
  jenkins_jenkins_home:
    external: true
