services:
  react-app:
    image: node:18-alpine
    container_name: secom_server
    user: root
    working_dir: /usr/src/app
    volumes:
      - jenkins_jenkins_home:/usr/src/app    # mount volume Jenkins
    ports:
      - "7012:5000"
    command: sh -c "cd workspace/secom/server && npm ci && npm install -g serve && serve -s build -l 5000"

volumes:
  jenkins_jenkins_home:
    external: true
