version: "3.9"

services:
  react-app:
    image: node:18-alpine
    container_name: secom_admin
    user: root
    working_dir: /usr/src/app
    volumes:
      - jenkins_jenkins_home:/usr/src/app    # mount volume Jenkins
    ports:
      - "7011:3000"
    command: sh -c "cd workspace/secom/admin && npm ci && npm run build && npm install -g serve && serve -s build -l 3000"

volumes:
  jenkins_jenkins_home:
    external: true
